#!/usr/bin/env python3
"""Plot expert-frame latent MSE relative to each episode's goal frame.

The default input is the latent cache produced by
experiments/cube_robot/experiments/latent_three_phase_mpc/run_experiment.py.
That cache was generated by encoding every rendered expert RGB frame and the
episode goal image with the frozen, pretrained LeWM visual encoder.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_DATASET = (
    PROJECT_ROOT
    / "experiments"
    / "cube_robot"
    / "experiments"
    / "latent_three_phase_mpc"
    / "outputs"
    / "data"
    / "three_phase_latents.npz"
)
DEFAULT_PLOT = PROJECT_ROOT / "expert_latent_goal_mse.png"
DEFAULT_CSV = PROJECT_ROOT / "expert_latent_goal_mse.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot one latent-to-goal MSE curve per expert episode and their "
            "step-aligned mean."
        )
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET,
        help="NPZ cache containing latents, goal_latents, and episode_ids.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_PLOT,
        help="Output image path.",
    )
    parser.add_argument(
        "--csv-output",
        type=Path,
        default=DEFAULT_CSV,
        help="Output path for the per-frame MSE values.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=220,
        help="Output image resolution.",
    )
    return parser.parse_args()


def load_episode_curves(
    dataset_path: Path,
) -> tuple[list[int], list[np.ndarray], list[bool], int]:
    with np.load(dataset_path) as dataset:
        required = {"latents", "goal_latents", "episode_ids"}
        missing = required.difference(dataset.files)
        if missing:
            raise KeyError(
                f"{dataset_path} is missing required arrays: {sorted(missing)}"
            )

        latents = np.asarray(dataset["latents"], dtype=np.float32)
        goal_latents = np.asarray(dataset["goal_latents"], dtype=np.float32)
        episode_ids = np.asarray(dataset["episode_ids"], dtype=np.int64)
        if "episode_successes" in dataset.files:
            sample_successes = np.asarray(
                dataset["episode_successes"], dtype=bool
            )
        else:
            sample_successes = np.ones(len(episode_ids), dtype=bool)

    if latents.shape != goal_latents.shape:
        raise ValueError(
            "latents and goal_latents must have the same shape, got "
            f"{latents.shape} and {goal_latents.shape}"
        )
    if latents.ndim != 2:
        raise ValueError(
            f"Expected [samples, latent_dim] arrays, got {latents.shape}"
        )
    if len(episode_ids) != len(latents):
        raise ValueError("episode_ids length does not match latent samples")

    sample_mse = np.mean(
        np.square(latents.astype(np.float64) - goal_latents.astype(np.float64)),
        axis=1,
    )
    unique_ids = np.unique(episode_ids)
    curves: list[np.ndarray] = []
    successes: list[bool] = []
    for episode_id in unique_ids:
        mask = episode_ids == episode_id
        curves.append(sample_mse[mask])
        successes.append(bool(np.all(sample_successes[mask])))

    return unique_ids.tolist(), curves, successes, int(latents.shape[1])


def step_aligned_mean(curves: list[np.ndarray]) -> np.ndarray:
    max_steps = max(len(curve) for curve in curves)
    aligned = np.full((len(curves), max_steps), np.nan, dtype=np.float64)
    for row, curve in enumerate(curves):
        aligned[row, : len(curve)] = curve
    return np.nanmean(aligned, axis=0)


def save_values_csv(
    output_path: Path,
    episode_ids: list[int],
    curves: list[np.ndarray],
    successes: list[bool],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(["episode_id", "step", "latent_goal_mse", "success"])
        for episode_id, curve, success in zip(
            episode_ids, curves, successes, strict=True
        ):
            for step, mse in enumerate(curve):
                writer.writerow(
                    [episode_id, step, f"{float(mse):.10g}", int(success)]
                )


def plot_curves(
    output_path: Path,
    episode_ids: list[int],
    curves: list[np.ndarray],
    mean_curve: np.ndarray,
    latent_dim: int,
    dpi: int,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(13.5, 7.6))

    color_map = plt.get_cmap("turbo")
    color_norm = mcolors.Normalize(
        vmin=min(episode_ids),
        vmax=max(episode_ids) if len(episode_ids) > 1 else min(episode_ids) + 1,
    )
    for episode_id, curve in zip(episode_ids, curves, strict=True):
        ax.plot(
            np.arange(len(curve)),
            curve,
            color=color_map(color_norm(episode_id)),
            linewidth=1.15,
            alpha=0.38,
        )

    steps = np.arange(len(mean_curve))
    ax.plot(
        steps,
        mean_curve,
        color="white",
        linewidth=5.5,
        alpha=0.95,
        zorder=4,
    )
    ax.plot(
        steps,
        mean_curve,
        color="#111827",
        linewidth=3.0,
        zorder=5,
    )

    ax.set_title(
        "Expert RGB Latent Distance to Goal",
        fontsize=17,
        fontweight="semibold",
        pad=14,
    )
    ax.set_xlabel("Environment step", fontsize=12)
    ax.set_ylabel(
        f"Latent MSE to goal frame ({latent_dim} dimensions)", fontsize=12
    )
    ax.grid(True, color="#cbd5e1", linewidth=0.8, alpha=0.5)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_xlim(left=0)
    ax.set_ylim(bottom=0)

    legend_handles = [
        Line2D(
            [0],
            [0],
            color=color_map(0.55),
            linewidth=1.5,
            alpha=0.55,
            label=f"Individual expert episodes (n={len(curves)})",
        ),
        Line2D(
            [0],
            [0],
            color="#111827",
            linewidth=3.0,
            label="Mean at each available step",
        ),
    ]
    ax.legend(handles=legend_handles, frameon=False, loc="upper right")

    scalar_map = plt.cm.ScalarMappable(norm=color_norm, cmap=color_map)
    scalar_map.set_array([])
    colorbar = fig.colorbar(scalar_map, ax=ax, pad=0.018, fraction=0.035)
    colorbar.set_label("Expert episode ID")

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    episode_ids, curves, successes, latent_dim = load_episode_curves(
        args.dataset
    )
    if not curves:
        raise ValueError(f"No expert episodes found in {args.dataset}")

    mean_curve = step_aligned_mean(curves)
    save_values_csv(args.csv_output, episode_ids, curves, successes)
    plot_curves(
        args.output,
        episode_ids,
        curves,
        mean_curve,
        latent_dim,
        args.dpi,
    )

    lengths = np.asarray([len(curve) for curve in curves])
    all_mse = np.concatenate(curves)
    print(f"Dataset: {args.dataset}")
    print(
        f"Episodes: {len(curves)} "
        f"(successful: {sum(successes)}/{len(successes)})"
    )
    print(
        f"Frames: {len(all_mse)}, latent dimension: {latent_dim}, "
        f"episode steps: {lengths.min()}-{lengths.max()} "
        f"(mean {lengths.mean():.2f})"
    )
    print(
        f"Latent MSE: min={all_mse.min():.8f}, "
        f"mean={all_mse.mean():.8f}, max={all_mse.max():.8f}"
    )
    print(f"Plot: {args.output}")
    print(f"CSV: {args.csv_output}")


if __name__ == "__main__":
    main()
